import localFont from "next/font/local";
import "./globals.css";

//components
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazirFont = localFont({
  src: "../public/font/fa/Vazirmatn[wght].ttf",
});
const gilroyFont = localFont({
  src: "../public/font/en/Gilroy-Regular.ttf",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${vazirFont.className} ${gilroyFont.className}`}
        // overflow-hidden
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
